# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2
jobs:
  build-test:
    docker:
      - image: circleci/python:3.7
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: "Build and test"
          command: |
            mkdir -p artifacts
            sudo pip --quiet install -r requirements.txt -t artifacts
            cp manage-mysql-user.py artifacts/
            ls -la artifacts
      - persist_to_workspace:
          root: ./
          paths:
            - artifacts

  package-publish-github-release:
    parallelism: 1
    docker:
      - image: cibuilds/github:0.10
    steps:
      - attach_workspace:
          at: ./
      - run:
          name: "Package and publish release on GitHub"
          command: |
            cd ./artifacts
            set +o pipefail
            LATEST_VERSION=$(curl --silent "https://api.github.com/repos/${CIRCLE_PROJECT_USERNAME}/${CIRCLE_PROJECT_REPONAME}/releases/latest" | jq -r '.tag_name // empty')
            set -o pipefail
            [  -z "$LATEST_VERSION" ] && LATEST_VERSION="0.0.0"
            VERSION=$(echo $LATEST_VERSION | awk -F. '{$NF = $NF + 1;} 1' | sed 's/ /./g')
            zip -r manage-mysql-user-$VERSION.zip *
            ghr -t ${GITHUB_TOKEN} -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -c ${CIRCLE_SHA1} -delete ${VERSION} manage-mysql-user-$VERSION.zip
workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build-test
      - package-publish-github-release:
          requires:
            - build-test
          filters:
            branches:
              only: master
